services:
  php:
    image: ghcr.io/thesis-php/php:${PHP_VERSION:-8.3}
    user: ${CONTAINER_USER:-}
    environment:
      HISTFILE: /app/var/.docker_history
      COMPOSER_CACHE_DIR: /app/var/.composer_cache
    tty: true
    volumes:
      - .:/app:cached
